name: Android CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permissions to Gradlew
      run: chmod +x ./gradlew  # This step grants execute permissions
    - name: Build with Gradle
      run: ./gradlew build
    - name: Convert line endings for Gradlew
      run: dos2unix ./gradlew
    - name: Upload APK
      uses: actions/upload-artifact@v2.1.4
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Check Gradlew Permissions
      run: ls -l ./gradlew
    - name: Check dos2unix Installation
      run: dos2unix --version
    - name: List APK Output Directory
      run: ls -l app/build/outputs/apk/debug/
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
          java-version: 11
